--------------------------------------------------------
--  ∆ƒ¿œ¿Ã ª˝º∫µ  - ∏Òø‰¿œ-5ø˘-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."POST" 
   (	"ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(20 CHAR), 
	"CONTENT" VARCHAR2(400 CHAR), 
	"AUTHOR" VARCHAR2(20 CHAR), 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT sysdate, 
	"MODIFIED_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.POST
SET DEFINE OFF;
Insert into SCOTT.POST (ID,TITLE,CONTENT,AUTHOR,CREATED_TIME,MODIFIED_TIME) values (101,'«œ¿Ã','«œ¿Ã','«œ¿Ã',to_timestamp('23/05/22 14:46:33.817000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/05/22 14:46:33.817000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SCOTT.POST (ID,TITLE,CONTENT,AUTHOR,CREATED_TIME,MODIFIED_TIME) values (102,'æ»≥Á','æ»≥Á','æ»≥Á',to_timestamp('23/05/22 16:17:41.274000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/05/22 16:17:41.274000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SCOTT.POST (ID,TITLE,CONTENT,AUTHOR,CREATED_TIME,MODIFIED_TIME) values (121,'¥Ò±€','¥Ò±€','«œ¿Ã',to_timestamp('23/05/24 13:36:18.928000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/05/24 13:36:18.928000000','RR/MM/DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index POSTS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."POSTS_ID_PK" ON "SCOTT"."POST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger POST_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."POST_TRG" 
BEFORE INSERT ON POST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT POST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."POST_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POST" MODIFY ("TITLE" CONSTRAINT "POSTS_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" MODIFY ("CONTENT" CONSTRAINT "POSTS_CONTENT_NN" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" MODIFY ("AUTHOR" CONSTRAINT "POSTS_AUTHOR_NN" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" ADD CONSTRAINT "POSTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
